import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/ThemeProvider"
import "./globals.css";
import { SessionProvider } from "next-auth/react"

import 'nprogress/nprogress.css';
import '../styles/nprogress-custom.css';

import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import SessionWrapper from "@/components/SessionWrapper";
import { ProgressBarProvider } from "@/components/Context/ProgressBarContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>

      <html lang="pt-br">
        <body className={` ${geistSans.variable} ${geistMono.variable} overflow-x-hidden`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark" // Você pode começar com o dark
            enableSystem={false} // Desabilita o tema do sistema para ter controle total
          >
            <ProgressBarProvider>
              {children}
            </ProgressBarProvider>
          </ThemeProvider>
        </body>
      </html>
    </SessionWrapper>

  );
}
